version: "3.7"

services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - 2015:2015
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/srv
      # - caddy_data:/data
      - caddy_config:/config

volumes:
  # caddy_data:
  #   external: true
  caddy_config:
networks:
  inner:
    external:
      name: inner-network
